using System.Collections.Generic;

namespace GreetyGreeter;

public enum GGLanguage { EN = 0, DE = 1, FR = 2, RU = 3, JA = 4 }

public static class Lang
{
    public static GGLanguage Current = GGLanguage.EN;

    private static readonly Dictionary<string, string[]> S = new()
    {
        { "windowTitle",       new[] { "Greety Greeter",          "Greety Greeter",           "Greety Greeter",         "Greety Greeter",              "Greety Greeter" } },
        { "greeted",           new[] { "Greeted",                  "Begrüßt",                  "Salués",                 "Поприветствовано",            "挨拶済み" } },
        { "settings",          new[] { "Settings",                 "Einstellungen",            "Paramètres",             "Настройки",                   "設定" } },
        { "zoneEnabled",       new[] { "Zone Active",              "Zone Aktiv",               "Zone Active",            "Зона Активна",                "ゾーン有効" } },
        { "zoneDisabled",      new[] { "Zone Inactive",            "Zone Inaktiv",             "Zone Inactive",          "Зона Неактивна",              "ゾーン無効" } },
        { "tabZone",           new[] { "Zone",                     "Zone",                     "Zone",                   "Зона",                        "ゾーン" } },
        { "tabGreet",          new[] { "Greet",                    "Begrüßung",                "Accueil",                "Приветствие",                 "挨拶" } },
        { "tabPresets",        new[] { "Presets",                  "Presets",                  "Préréglages",            "Пресеты",                     "プリセット" } },
        { "tabMemory",         new[] { "Memory",                   "Gedächtnis",               "Mémoire",                "Память",                      "メモリ" } },
        { "tabLanguage",       new[] { "Language",                 "Sprache",                  "Langue",                 "Язык",                        "言語" } },
        { "shape",             new[] { "Shape",                    "Form",                     "Forme",                  "Форма",                       "形状" } },
        { "sphere",            new[] { "Sphere",                   "Sphäre",                   "Sphère",                 "Сфера",                       "球体" } },
        { "cube",              new[] { "Cube",                     "Würfel",                   "Cube",                   "Куб",                         "立方体" } },
        { "radius",            new[] { "Radius",                   "Radius",                   "Rayon",                  "Радиус",                      "半径" } },
        { "width",             new[] { "Width",                    "Breite",                   "Largeur",                "Ширина",                      "幅" } },
        { "height",            new[] { "Height",                   "Höhe",                     "Hauteur",                "Высота",                      "高さ" } },
        { "depth",             new[] { "Depth",                    "Tiefe",                    "Profondeur",             "Глубина",                     "奥行き" } },
        { "showVisual",        new[] { "Show Zone Visual",         "Zone anzeigen",            "Afficher la zone",       "Показать зону",               "ゾーン表示" } },
        { "capturePos",        new[] { "To My Feet",               "Zu meinen Füßen",          "À mes pieds",           "К моим ногам",                "足元に設定" } },
        { "zoneCenter",        new[] { "Zone Center",              "Zonenmitte",               "Centre de zone",         "Центр зоны",                  "ゾーン中心" } },
        { "posX",              new[] { "X",                        "X",                        "X",                      "X",                           "X" } },
        { "posY",              new[] { "Y",                        "Y",                        "Y",                      "Y",                           "Y" } },
        { "posZ",              new[] { "Z",                        "Z",                        "Z",                      "Z",                           "Z" } },
        { "rotation",          new[] { "Rotation (Y°)",            "Rotation (Y°)",            "Rotation (Y°)",          "Поворот (Y°)",                "回転 (Y°)" } },
        { "showRootBone",      new[] { "Show Player Root-Bone Dots","Spieler-Fußpunkte anzeigen","Afficher les points de pied","Показывать точки у ног","プレイヤーの足元表示" } },
        { "tabColors",         new[] { "Colors",                   "Farben",                   "Couleurs",               "Цвета",                       "カラー" } },
        { "colorZoneXZ",       new[] { "Sphere XZ (horizontal)",   "Sphäre XZ (horizontal)",   "Sphère XZ (horizontal)", "Сфера XZ (горизонт.)",        "球 XZ (水平)" } },
        { "colorZoneXY",       new[] { "Sphere XY (vertical N-S)", "Sphäre XY (vertikal N-S)", "Sphère XY (vert. N-S)",  "Сфера XY (верт. С-Ю)",       "球 XY (縦N-S)" } },
        { "colorZoneYZ",       new[] { "Sphere YZ (vertical E-W)", "Sphäre YZ (vertikal O-W)", "Sphère YZ (vert. E-W)",  "Сфера YZ (верт. В-З)",       "球 YZ (縦E-W)" } },
        { "colorZoneCube",     new[] { "Cube edges",               "Würfelkanten",             "Arêtes du cube",         "Рёбра куба",                  "箱の辺" } },
        { "colorGreeting",     new[] { "Greeting (active)",        "Begrüßung (aktiv)",        "Salutation (active)",    "Приветствие (активное)",      "挨拶中" } },
        { "colorGreeted",      new[] { "Greeted (on cooldown)",    "Begrüßt (Cooldown aktiv)", "Salué (délai actif)",    "Поприветствован (перезарядка)","挨拶済み (CD中)" } },
        { "colorAgainToGreet", new[] { "Again to Greet",           "Erneut zu begrüßen",       "À saluer à nouveau",     "Снова приветствовать",        "再挨拶対象" } },
        { "sectionZoneColors", new[] { "Zone Line Colors",         "Zonen-Linienfarben",       "Couleurs des lignes",    "Цвета линий зоны",            "ゾーン線の色" } },
        { "sectionListColors", new[] { "Player List Colors",       "Spielerlisten-Farben",     "Couleurs de la liste",   "Цвета списка игроков",        "プレイヤーリストの色" } },
        { "statusGreeting",    new[] { "Greeting",                 "Begrüßend",                "Saluation",              "Приветствие",                 "挨拶中" } },
        { "statusGreeted",     new[] { "Greeted",                  "Begrüßt",                  "Salué",                  "Поприветствован",             "挨拶済み" } },
        { "statusAgainToGreet",new[] { "Again to Greet",           "Erneut begrüßen",          "À saluer à nouveau",     "Снова приветствовать",        "再挨拶" } },
        { "cooldown",          new[] { "Cooldown",                 "Abklingzeit",              "Délai",                  "Задержка",                    "クールダウン" } },
        { "cooldownHint",      new[] { "Min. time between greets", "Mindestzeit zwischen Begrüßungen", "Délai min. entre saluts", "Мин. время между приветствиями", "挨拶間隔" } },
        { "targetPlayer",      new[] { "Target Player During Execution", "Spieler anvisieren während Ausführung", "Cibler le joueur pendant l'exécution", "Нацелиться на игрока при выполнении", "実行中プレイヤーをターゲット" } },
        { "activePreset",      new[] { "Active Preset",           "Aktives Preset",           "Préréglage actif",       "Активный пресет",             "有効プリセット" } },
        { "noPreset",          new[] { "— No Preset —",           "— Kein Preset —",          "— Aucun préréglage —",  "— Нет пресета —",             "— プリセットなし —" } },
        { "addPreset",         new[] { "+ New Preset",            "+ Neues Preset",           "+ Nouveau préréglage",  "+ Новый пресет",              "+ 新規プリセット" } },
        { "deletePreset",      new[] { "Delete",                  "Löschen",                  "Supprimer",              "Удалить",                     "削除" } },
        { "renamePreset",      new[] { "Rename",                  "Umbenennen",               "Renommer",               "Переименовать",               "名前変更" } },
        { "savePreset",        new[] { "Overwrite Preset",        "Preset überschreiben",     "Écraser le préréglage", "Перезаписать пресет",         "プリセット上書き" } },
        { "commandLines",      new[] { "Command Lines",           "Befehlszeilen",            "Lignes de commandes",    "Строки команд",               "コマンドライン" } },
        { "addLine",           new[] { "+ Add Line",              "+ Zeile hinzufügen",       "+ Ajouter une ligne",   "+ Добавить строку",           "+ 行を追加" } },
        { "lineText",          new[] { "Command",                 "Befehl",                   "Commande",               "Команда",                     "コマンド" } },
        { "lineDelay",         new[] { "Delay (s)",               "Verzögerung (s)",          "Délai (s)",              "Задержка (с)",                "遅延 (秒)" } },
        { "tellHint",          new[] { "/tell detected – min. 1.1s", "/tell erkannt – mind. 1.1s", "/tell détecté – min. 1.1s", "/tell обнаружен – мин. 1.1с", "/tell検出 – 最低1.1秒" } },
        { "tokenHint",         new[] { "Use <t> as player placeholder (Name@World)", "<t> als Spieler-Platzhalter verwenden (Name@Welt)", "Utilisez <t> comme espace réservé au joueur", "Используйте <t> как заполнитель игрока", "<t>をプレイヤーのプレースホルダーとして使用" } },
        { "totalGreeted",      new[] { "Total greeted",           "Gesamt begrüßt",           "Total salués",           "Всего поприветствовано",      "合計挨拶数" } },
        { "resetCount",        new[] { "Reset",                   "Zurücksetzen",             "Réinitialiser",          "Сбросить",                    "リセット" } },
        { "clearMemory",       new[] { "Clear All Memory",        "Gedächtnis leeren",        "Effacer la mémoire",     "Очистить память",             "メモリをクリア" } },
        { "memColName",        new[] { "Name",                    "Name",                     "Nom",                    "Имя",                         "名前" } },
        { "memColWorld",       new[] { "World",                   "Welt",                     "Monde",                  "Мир",                         "ワールド" } },
        { "memColFirst",       new[] { "First Seen",              "Erstkontakt",              "Premier contact",        "Первый контакт",              "初回" } },
        { "memColLast",        new[] { "Last Seen",               "Letzter Kontakt",          "Dernier contact",        "Последний контакт",           "最終" } },
        { "languageLabel",     new[] { "Interface Language",      "Oberflächensprache",       "Langue de l'interface", "Язык интерфейса",             "インターフェース言語" } },
        { "moveUp",            new[] { "Up",                      "Hoch",                     "Haut",                   "Вверх",                       "上へ" } },
        { "moveDown",          new[] { "Down",                    "Runter",                   "Bas",                    "Вниз",                        "下へ" } },
        { "deleteHint",        new[] { "Ctrl+Click to delete",    "Strg+Klick zum Löschen",   "Ctrl+Clic pour supprimer", "Ctrl+Клик для удаления",   "Ctrl+クリックで削除" } },
        { "clearHint",         new[] { "Ctrl+Click to clear all", "Strg+Klick zum Leeren",    "Ctrl+Clic pour tout effacer", "Ctrl+Клик для очистки", "Ctrl+クリックで全消去" } },
        { "resetHint",         new[] { "Shift+Click to reset",    "Shift+Klick zum Zurücksetzen", "Maj+Clic pour réinitialiser", "Shift+Клик для сброса", "Shift+クリックでリセット" } },
        { "noLines",           new[] { "No command lines. Add one below.", "Keine Zeilen. Unten hinzufügen.", "Aucune ligne. Ajoutez-en une ci-dessous.", "Нет строк. Добавьте ниже.", "コマンドラインなし。下に追加してください。" } },
        { "noMemory",          new[] { "No players greeted yet.", "Noch keine Spieler begrüßt.", "Aucun joueur salué pour l'instant.", "Ещё нет приветствованных игроков.", "まだ挨拶したプレイヤーはいません。" } },
        { "presetName",        new[] { "Preset Name",             "Preset-Name",              "Nom du préréglage",      "Название пресета",            "プリセット名" } },
        { "queueCount",          new[] { "Queue",                        "Warteschlange",                       "File d'attente",                  "Очередь",                                  "キュー" } },
        { "tabIgnoreList",       new[] { "Ignore-List",                  "Ignore-Liste",                        "Liste d'exclusion",               "Список игнорирования",                     "無視リスト" } },
        { "ignoreListInputHint", new[] { "Player name…",                 "Spielername…",                        "Nom du joueur…",                  "Имя игрока…",                              "プレイヤー名…" } },
        { "ignoreListAdd",       new[] { "Add",                          "Hinzufügen",                          "Ajouter",                         "Добавить",                                 "追加" } },
        { "ignoreListEmpty",     new[] { "No players ignored.",           "Keine Spieler ignoriert.",             "Aucun joueur ignoré.",             "Список пуст.",                             "無視リストは空です。" } },
        { "ignoreListHint",      new[] { "Listed players never trigger a greeting (world is ignored).", "Gelistete Spieler lösen nie eine Begrüßung aus (Welt wird ignoriert).", "Les joueurs listés ne déclenchent jamais de salutation (monde ignoré).", "Перечисленные игроки никогда не вызывают приветствие (мир игнорируется).", "リスト内のプレイヤーは挨拶をトリガーしません（ワールド無視）。" } },
        { "tabSchedule",         new[] { "Schedule",                     "Zeitplan",                            "Planning",                        "Расписание",                               "スケジュール" } },
        { "scheduleHint",        new[] { "Override the active preset during the given time window. First matching entry wins. Overnight ranges (e.g. 22:00–06:00) are supported.", "Überschreibt das aktive Preset im angegebenen Zeitfenster. Der erste Treffer gewinnt. Nacht-übergreifende Zeiten (z. B. 22:00–06:00) werden unterstützt.", "Remplace le préréglage actif pendant la plage horaire donnée. Le premier résultat l'emporte. Les plages nocturnes sont supportées.", "Заменяет активный пресет в указанное время. Побеждает первое совпадение. Поддерживаются ночные диапазоны.", "指定した時間帯にアクティブプリセットを上書きします。最初の一致が優先。深夜をまたぐ範囲も対応。" } },
        { "scheduleAdd",         new[] { "+ Add Schedule",               "+ Zeitplan hinzufügen",               "+ Ajouter un horaire",            "+ Добавить расписание",                    "+ スケジュール追加" } },
        { "scheduleEmpty",       new[] { "No schedules configured.",      "Kein Zeitplan konfiguriert.",         "Aucun horaire configuré.",        "Расписаний нет.",                          "スケジュールなし。" } },
        { "scheduleNoPresets",   new[] { "Add a preset first.",           "Zuerst ein Preset anlegen.",          "Ajoutez d'abord un préréglage.",  "Сначала создайте пресет.",                 "先にプリセットを作成してください。" } },
    };

    public static string T(string key) => S.TryGetValue(key, out var a) ? a[(int)Current] : key;
}
